In [2]:
import torch
x = torch.tensor([0.], requires_grad=True)
zero = torch.tensor([0.])
f = torch.square(torch.max(x,zero))
f.backward()
print(x.grad) #prints the gradient of f with respect to x at its current value

tensor([0.])


In [3]:
x = torch.tensor([0.], requires_grad=True)
zero = torch.tensor([0.])
f = torch.min(x, zero) + torch.max(x,zero)
f.backward()
print(x.grad) #prints the gradient of f with respect to x at its current value

tensor([1.])


In [5]:
x = torch.tensor([1e-50], requires_grad=True)
zero = torch.tensor([0.])
f = torch.min(x, zero) + torch.max(x,zero)
f.backward()
print(x.grad) #prints the gradient of f with respect to x at its current value

tensor([1.])


In [6]:
x = torch.tensor([1e-30], requires_grad=True)
zero = torch.tensor([0.])
f = torch.min(x, zero) + torch.max(x,zero)
f.backward()
print(x.grad) #prints the gradient of f with respect to x at its current value

tensor([1.])


In [8]:
x = torch.tensor([0.], requires_grad=True)
zero = torch.tensor([0.])
f = torch.min(torch.abs(x), x)
f.backward()
print(x.grad) #prints the gradient of f with respect to x at its current value

tensor([0.5000])


In [ ]:
x = torch.tensor([0.], requires_grad=True)
zero = torch.tensor([0.])
f = torch.min(x, torch.abs(x))
f.backward()
print(x.grad) #prints the gradient of f with respect to x at its current value